unit DelphiNetCDF;

interface

uses
  Winapi.Windows;

// NetCDF C documentation: http://www.unidata.ucar.edu/software/netcdf/docs/

const
  DLLNAME = 'netcdf.dll';

type
  TNCType = Integer;  // e.g. NC_NAT, NC_BYTE, NC_CHAR, ...
  PNCType = ^TNCType;

  TNCVlen = record
    len: SIZE_T;
    p: Pointer;
  end;

  PNCVlen = ^TNCVlen;

const
// const values converted from C #defines using this regex: #define\s+?([_a-zA-Z0-9]+)\s+?([-_a-zA-Z0-9()]+)

  NC_NAT = 0;
  NC_BYTE = 1;
  NC_CHAR = 2;
  NC_SHORT = 3;
  NC_INT = 4;
  NC_LONG = NC_INT;
  NC_FLOAT = 5;
  NC_DOUBLE = 6;
  NC_UBYTE = 7;
  NC_USHORT = 8;
  NC_UINT = 9;
  NC_INT64 = 10;
  NC_UINT64 = 11;
  NC_STRING = 12;
  NC_MAX_ATOMIC_TYPE = NC_STRING;
  NC_VLEN = 13;
  NC_OPAQUE = 14;
  NC_ENUM = 15;
  NC_COMPOUND = 1;
  NC_FIRSTUSERTYPEID = 32;
  _FillValue =	'_FillValue';
  NC_FILL = 0;
  NC_NOFILL = $100;
  NC_NOWRITE = $0000;
  NC_WRITE = $0001;
  NC_CLOBBER = $0000;
  NC_NOCLOBBER = $0004;
  NC_DISKLESS = $0008;
  NC_MMAP = $0010;
  NC_64BIT_DATA = $0020;
  NC_CDF5 = NC_64BIT_DATA;
  NC_CLASSIC_MODEL = $0100;
  NC_64BIT_OFFSET = $0200;
  NC_LOCK = $0400;
  NC_SHARE = $0800;
  NC_NETCDF4 = $1000;
  NC_MPIIO = $2000;
  NC_MPIPOSIX = $4000;
  NC_INMEMORY = $8000;
  NC_PNETCDF = (NC_MPIIO);
  NC_FORMAT_CLASSIC = (1);
  NC_FORMAT_64BIT_OFFSET = (2);
  NC_FORMAT_64BIT = (NC_FORMAT_64BIT_OFFSET);
  NC_FORMAT_NETCDF4 = (3);
  NC_FORMAT_NETCDF4_CLASSIC = (4);
  NC_FORMAT_64BIT_DATA = (5);
  NC_FORMAT_CDF5 = NC_FORMAT_64BIT_DATA;
  NC_FORMATX_NC3 = (1);
  NC_FORMATX_NC_HDF5 = (2);
  NC_FORMATX_NC4 = NC_FORMATX_NC_HDF5;
  NC_FORMATX_NC_HDF4 = (3);
  NC_FORMATX_PNETCDF = (4);
  NC_FORMATX_DAP2 = (5);
  NC_FORMATX_DAP4 = (6);
  NC_FORMATX_UNDEFINED = (0);
  NC_FORMAT_NC3 = NC_FORMATX_NC3;
  NC_FORMAT_NC_HDF5 = NC_FORMATX_NC_HDF5;
  NC_FORMAT_NC4 = NC_FORMATX_NC4;
  NC_FORMAT_NC_HDF4 = NC_FORMATX_NC_HDF4;
  NC_FORMAT_PNETCDF = NC_FORMATX_PNETCDF;
  NC_FORMAT_DAP2 = NC_FORMATX_DAP2;
  NC_FORMAT_DAP4 = NC_FORMATX_DAP4;
  NC_FORMAT_UNDEFINED = NC_FORMATX_UNDEFINED;
  NC_SIZEHINT_DEFAULT = 0;
  NC_ALIGN_CHUNK = -1;
  NC_UNLIMITED = 0;
  NC_GLOBAL = -1;
  NC_MAX_DIMS = 1024;
  NC_MAX_ATTRS = 8192;
  NC_MAX_VARS = 8192;
  NC_MAX_NAME = 256;
  NC_MAX_VAR_DIMS = 1024;
  NC_MAX_HDF4_NAME = 64;
  NC_ENDIAN_NATIVE = 0;
  NC_ENDIAN_LITTLE = 1;
  NC_ENDIAN_BIG = 2;
  NC_CHUNKED = 0;
  NC_CONTIGUOUS = 1;
  NC_NOCHECKSUM = 0;
  NC_FLETCHER32 = 1;
  NC_NOSHUFFLE = 0;
  NC_SHUFFLE = 1;
  NC_NOERR = 0;
  NC2_ERR = (-1);
  NC_EBADID = (-33);
  NC_ENFILE = (-34);
  NC_EEXIST = (-35);
  NC_EINVAL = (-36);
  NC_EPERM = (-37);
  NC_ENOTINDEFINE = (-38);
  NC_EINDEFINE = (-39);
  NC_EINVALCOORDS = (-40);
  NC_EMAXDIMS = (-41);
  NC_ENAMEINUSE = (-42);
  NC_ENOTATT = (-43);
  NC_EMAXATTS = (-44);
  NC_EBADTYPE = (-45);
  NC_EBADDIM = (-46);
  NC_EUNLIMPOS = (-47);
  NC_EMAXVARS = (-48);
  NC_ENOTVAR = (-49);
  NC_EGLOBAL = (-50);
  NC_ENOTNC = (-51);
  NC_ESTS = (-52);
  NC_EMAXNAME = (-53);
  NC_EUNLIMIT = (-54);
  NC_ENORECVARS = (-55);
  NC_ECHAR = (-56);
  NC_EEDGE = (-57);
  NC_ESTRIDE = (-58);
  NC_EBADNAME = (-59);
  NC_ERANGE = (-60);
  NC_ENOMEM = (-61);
  NC_EVARSIZE = (-62);
  NC_EDIMSIZE = (-63);
  NC_ETRUNC = (-64);
  NC_EAXISTYPE = (-65);
  NC_EDAP = (-66);
  NC_ECURL = (-67);
  NC_EIO = (-68);
  NC_ENODATA = (-69);
  NC_EDAPSVC = (-70);
  NC_EDAS = (-71);
  NC_EDDS = (-72);
  NC_EDMR = NC_EDDS;
  NC_EDATADDS = (-73);
  NC_EDATADAP = NC_EDATADDS;
  NC_EDAPURL = (-74);
  NC_EDAPCONSTRAINT = (-75);
  NC_ETRANSLATION = (-76);
  NC_EACCESS = (-77);
  NC_EAUTH = (-78);
  NC_ENOTFOUND = (-90);
  NC_ECANTREMOVE = (-91);
  NC4_FIRST_ERROR = (-100);
  NC_EHDFERR = (-101);
  NC_ECANTREAD = (-102);
  NC_ECANTWRITE = (-103);
  NC_ECANTCREATE = (-104);
  NC_EFILEMETA = (-105);
  NC_EDIMMETA = (-106);
  NC_EATTMETA = (-107);
  NC_EVARMETA = (-108);
  NC_ENOCOMPOUND = (-109);
  NC_EATTEXISTS = (-110);
  NC_ENOTNC4 = (-111);
  NC_ESTRICTNC3 = (-112);
  NC_ENOTNC3 = (-113);
  NC_ENOPAR = (-114);
  NC_EPARINIT = (-115);
  NC_EBADGRPID = (-116);
  NC_EBADTYPID = (-117);
  NC_ETYPDEFINED = (-118);
  NC_EBADFIELD = (-119);
  NC_EBADCLASS = (-120);
  NC_EMAPTYPE = (-121);
  NC_ELATEFILL = (-122);
  NC_ELATEDEF = (-123);
  NC_EDIMSCALE = (-124);
  NC_ENOGRP = (-125);
  NC_ESTORAGE = (-126);
  NC_EBADCHUNK = (-127);
  NC_ENOTBUILT = (-128);
  NC_EDISKLESS = (-129);
  NC_ECANTEXTEND = (-130);
  NC_EMPI = (-131);
  NC4_LAST_ERROR = (-131);
  DIM_WITHOUT_VARIABLE = 'This is a netCDF dimension but not a netCDF variable.';
  NC_HAVE_NEW_CHUNKING_API = 1;
  NC_EURL = (NC_EDAPURL);
  NC_ECONSTRAINT = (NC_EDAPCONSTRAINT);
  MAX_NC_DIMS = NC_MAX_DIMS;
  MAX_NC_ATTRS = NC_MAX_ATTRS;
  MAX_NC_VARS = NC_MAX_VARS;
  MAX_NC_NAME = NC_MAX_NAME;
  MAX_VAR_DIMS = NC_MAX_VAR_DIMS;
  NC_ENTOOL = NC_EMAXNAME;
  NC_EXDR = (-32);
  NC_SYSERR = (-31);
  NC_FATAL = 1;
  NC_VERBOSE = 2;
  NC_FILL_BYTE: AnsiChar = AnsiChar(-127);
  NC_FILL_CHAR: AnsiChar = #0;
  NC_FILL_SHORT: SmallInt = -32767;
  NC_FILL_INT: Integer = -2147483647;
  NC_FILL_FLOAT: Single = 9.9692099683868690e36;
  NC_FILL_DOUBLE: Double = 9.9692099683868690e36;
  NC_FILL_UBYTE: Byte = 255;
  NC_FILL_USHORT: Word = 65535;
  NC_FILL_UINT: Cardinal = 4294967295;
  NC_FILL_INT64: Int64 = -9223372036854775806;
  NC_FILL_UINT64: UInt64 = 18446744073709551614;
  NC_FILL_STRING = nil;  // ?????

function nc_inq_libvers(): PAnsiChar; cdecl; external DLLNAME;
function nc_strerror(ncerr: Integer): PAnsiChar; cdecl; external DLLNAME;
function nc__create(path: PAnsiChar; cmode: Integer; initialsz: SIZE_T; chunksizehintp: PSIZE_T; ncidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_create(path: PAnsiChar; cmode: Integer; ncidp: PInteger): Integer; cdecl; external DLLNAME;
function nc__open(path: PAnsiChar; mode: Integer; chunksizehintp: PSIZE_T; ncidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_open(path: PAnsiChar; mode: Integer; ncidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_path(ncid: Integer; pathlen: PSIZE_T; path: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_ncid(ncid: Integer; name: PAnsiChar; grp_ncid: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_grps(ncid: Integer; numgrps: PInteger; ncids: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_grpname(ncid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_grpname_full(ncid: Integer; lenp: PSIZE_T; full_name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_grpname_len(ncid: Integer; lenp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_grp_parent(ncid: Integer; parent_ncid: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_grp_ncid(ncid: Integer; grp_name: PAnsiChar; grp_ncid: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_grp_full_ncid(ncid: Integer; full_name: PAnsiChar; grp_ncid: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_varids(ncid: Integer; nvars: PInteger; varids: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_dimids(ncid: Integer; ndims: PInteger; dimids: PInteger; include_parents: Integer): Integer; cdecl; external DLLNAME;
function nc_inq_typeids(ncid: Integer; ntypes: PInteger; typeids: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_type_equal(ncid1: Integer; typeid1: TNCType; ncid2: Integer; typeid2: TNCType; equal: PInteger): Integer; cdecl; external DLLNAME;
function nc_def_grp(parent_ncid: Integer; name: PAnsiChar; new_ncid: PInteger): Integer; cdecl; external DLLNAME;
function nc_rename_grp(grpid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_def_compound(ncid: Integer; size: SIZE_T; name: PAnsiChar; typeidp: PNCType): Integer; cdecl; external DLLNAME;
function nc_insert_compound(ncid: Integer; xtype: TNCType; name: PAnsiChar; offset: SIZE_T; field_typeid: TNCType): Integer; cdecl; external DLLNAME;
function nc_insert_array_compound(ncid: Integer; xtype: TNCType; name: PAnsiChar; offset: SIZE_T; field_typeid: TNCType; ndims: Integer; dim_sizes: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_type(ncid: Integer; xtype: TNCType; name: PAnsiChar; size: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_typeid(ncid: Integer; name: PAnsiChar; typeidp: PNCType): Integer; cdecl; external DLLNAME;
function nc_inq_compound(ncid: Integer; xtype: TNCType; name: PAnsiChar; sizep: PSIZE_T; nfieldsp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_compound_name(ncid: Integer; xtype: TNCType; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_compound_size(ncid: Integer; xtype: TNCType; sizep: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_compound_nfields(ncid: Integer; xtype: TNCType; nfieldsp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_compound_field(ncid: Integer; xtype: TNCType; fieldid: Integer; name: PAnsiChar; offsetp: PSIZE_T; field_typeidp: PNCType; ndimsp: PInteger; dim_sizesp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_compound_fieldname(ncid: Integer; xtype: TNCType; fieldid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_compound_fieldindex(ncid: Integer; xtype: TNCType; name: PAnsiChar; fieldidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_compound_fieldoffset(ncid: Integer; xtype: TNCType; fieldid: Integer; offsetp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_compound_fieldtype(ncid: Integer; xtype: TNCType; fieldid: Integer; field_typeidp: PNCType): Integer; cdecl; external DLLNAME;
function nc_inq_compound_fieldndims(ncid: Integer; xtype: TNCType; fieldid: Integer; ndimsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_compound_fielddim_sizes(ncid: Integer; xtype: TNCType; fieldid: Integer; dim_sizes: PInteger): Integer; cdecl; external DLLNAME;
function nc_def_vlen(ncid: Integer; name: PAnsiChar; base_typeid: TNCType; xtypep: PNCType): Integer; cdecl; external DLLNAME;
function nc_inq_vlen(ncid: Integer; xtype: TNCType; name: PAnsiChar; datum_sizep: PSIZE_T; base_nc_typep: PNCType): Integer; cdecl; external DLLNAME;
function nc_free_vlen(vl: PNCVlen): Integer; cdecl; external DLLNAME;
function nc_free_vlens(len: SIZE_T; vlens: PNCVlen): Integer; cdecl; external DLLNAME;
function nc_put_vlen_element(ncid: Integer; typeid1: Integer; vlen_element: Pointer; len: SIZE_T; data: Pointer): Integer; cdecl; external DLLNAME;
function nc_get_vlen_element(ncid: Integer; typeid1: Integer; vlen_element: Pointer; len: PSIZE_T; data: Pointer): Integer; cdecl; external DLLNAME;
function nc_free_string(len: SIZE_T; data: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_user_type(ncid: Integer; xtype: TNCType; name: PAnsiChar; size: PSIZE_T; base_nc_typep: PNCType; nfieldsp: PSIZE_T; classp: PInteger): Integer; cdecl; external DLLNAME;
function nc_put_att(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: Pointer): Integer; cdecl; external DLLNAME;
function nc_get_att(ncid: Integer; varid: Integer; name: PAnsiChar; ip: Pointer): Integer; cdecl; external DLLNAME;
function nc_def_enum(ncid: Integer; base_typeid: TNCType; name: PAnsiChar; typeidp: PNCType): Integer; cdecl; external DLLNAME;
function nc_insert_enum(ncid: Integer; xtype: TNCType; name: PAnsiChar; value: Pointer): Integer; cdecl; external DLLNAME;
function nc_inq_enum(ncid: Integer; xtype: TNCType; name: PAnsiChar; base_nc_typep: PNCType; base_sizep: PSIZE_T; num_membersp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_enum_member(ncid: Integer; xtype: TNCType; idx: Integer; name: PAnsiChar; value: Pointer): Integer; cdecl; external DLLNAME;
function nc_inq_enum_ident(ncid: Integer; xtype: TNCType; value: Int64; identifier: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_def_opaque(ncid: Integer; size: SIZE_T; name: PAnsiChar; xtypep: PNCType): Integer; cdecl; external DLLNAME;
function nc_inq_opaque(ncid: Integer; xtype: TNCType; name: PAnsiChar; sizep: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_put_var(ncid: Integer; varid: Integer; op: Pointer): Integer; cdecl; external DLLNAME;
function nc_get_var(ncid: Integer; varid: Integer; ip: Pointer): Integer; cdecl; external DLLNAME;
function nc_put_var1(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: Pointer): Integer; cdecl; external DLLNAME;
function nc_get_var1(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: Pointer): Integer; cdecl; external DLLNAME;
function nc_put_vara(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: Pointer): Integer; cdecl; external DLLNAME;
function nc_get_vara(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: Pointer): Integer; cdecl; external DLLNAME;
function nc_put_vars(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: Pointer): Integer; cdecl; external DLLNAME;
function nc_get_vars(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: Pointer): Integer; cdecl; external DLLNAME;
function nc_put_varm(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: Pointer): Integer; cdecl; external DLLNAME;
function nc_get_varm(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: Pointer): Integer; cdecl; external DLLNAME;
function nc_def_var_deflate(ncid: Integer; varid: Integer; shuffle: Integer; deflate: Integer; deflate_level: Integer): Integer; cdecl; external DLLNAME;
function nc_inq_var_deflate(ncid: Integer; varid: Integer; shufflep: PInteger; deflatep: PInteger; deflate_levelp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_var_szip(ncid: Integer; varid: Integer; options_maskp: PInteger; pixels_per_blockp: PInteger): Integer; cdecl; external DLLNAME;
function nc_def_var_fletcher32(ncid: Integer; varid: Integer; fletcher32: Integer): Integer; cdecl; external DLLNAME;
function nc_inq_var_fletcher32(ncid: Integer; varid: Integer; fletcher32p: PInteger): Integer; cdecl; external DLLNAME;
function nc_def_var_chunking(ncid: Integer; varid: Integer; storage: Integer; chunksizesp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_var_chunking(ncid: Integer; varid: Integer; storagep: PInteger; chunksizesp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_def_var_fill(ncid: Integer; varid: Integer; no_fill: Integer; fill_value: Pointer): Integer; cdecl; external DLLNAME;
function nc_inq_var_fill(ncid: Integer; varid: Integer; no_fill: PInteger; fill_valuep: Pointer): Integer; cdecl; external DLLNAME;
function nc_def_var_endian(ncid: Integer; varid: Integer; endian: Integer): Integer; cdecl; external DLLNAME;
function nc_inq_var_endian(ncid: Integer; varid: Integer; endianp: PInteger): Integer; cdecl; external DLLNAME;
function nc_set_fill(ncid: Integer; fillmode: Integer; old_modep: PInteger): Integer; cdecl; external DLLNAME;
function nc_set_default_format(format: Integer; old_formatp: PInteger): Integer; cdecl; external DLLNAME;
function nc_set_chunk_cache(size: SIZE_T; nelems: SIZE_T; preemption: Single): Integer; cdecl; external DLLNAME;
function nc_get_chunk_cache(sizep: PSIZE_T; nelemsp: PSIZE_T; preemptionp: PSingle): Integer; cdecl; external DLLNAME;
function nc_set_var_chunk_cache(ncid: Integer; varid: Integer; size: SIZE_T; nelems: SIZE_T; preemption: Single): Integer; cdecl; external DLLNAME;
function nc_get_var_chunk_cache(ncid: Integer; varid: Integer; sizep: PSIZE_T; nelemsp: PSIZE_T; preemptionp: PSingle): Integer; cdecl; external DLLNAME;
function nc_redef(ncid: Integer): Integer; cdecl; external DLLNAME;
function nc__enddef(ncid: Integer; h_minfree: SIZE_T; v_align: SIZE_T; v_minfree: SIZE_T; r_align: SIZE_T): Integer; cdecl; external DLLNAME;
function nc_enddef(ncid: Integer): Integer; cdecl; external DLLNAME;
function nc_sync(ncid: Integer): Integer; cdecl; external DLLNAME;
function nc_abort(ncid: Integer): Integer; cdecl; external DLLNAME;
function nc_close(ncid: Integer): Integer; cdecl; external DLLNAME;
function nc_inq(ncid: Integer; ndimsp: PInteger; nvarsp: PInteger; nattsp: PInteger; unlimdimidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_ndims(ncid: Integer; ndimsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_nvars(ncid: Integer; nvarsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_natts(ncid: Integer; nattsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_unlimdim(ncid: Integer; unlimdimidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_unlimdims(ncid: Integer; nunlimdimsp: PInteger; unlimdimidsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_format(ncid: Integer; formatp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_format_extended(ncid: Integer; formatp: PInteger; modep: PInteger): Integer; cdecl; external DLLNAME;
function nc_def_dim(ncid: Integer; name: PAnsiChar; len: SIZE_T; idp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_dimid(ncid: Integer; name: PAnsiChar; idp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_dim(ncid: Integer; dimid: Integer; name: PAnsiChar; lenp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_dimname(ncid: Integer; dimid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_dimlen(ncid: Integer; dimid: Integer; lenp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_rename_dim(ncid: Integer; dimid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_att(ncid: Integer; varid: Integer; name: PAnsiChar; xtypep: PNCType; lenp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_attid(ncid: Integer; varid: Integer; name: PAnsiChar; idp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_atttype(ncid: Integer; varid: Integer; name: PAnsiChar; xtypep: PNCType): Integer; cdecl; external DLLNAME;
function nc_inq_attlen(ncid: Integer; varid: Integer; name: PAnsiChar; lenp: PSIZE_T): Integer; cdecl; external DLLNAME;
function nc_inq_attname(ncid: Integer; varid: Integer; attnum: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_copy_att(ncid_in: Integer; varid_in: Integer; name: PAnsiChar; ncid_out: Integer; varid_out: Integer): Integer; cdecl; external DLLNAME;
function nc_rename_att(ncid: Integer; varid: Integer; name: PAnsiChar; newname: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_del_att(ncid: Integer; varid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_att_text(ncid: Integer; varid: Integer; name: PAnsiChar; len: SIZE_T; op: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_att_text(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_att_string(ncid: Integer; varid: Integer; name: PAnsiChar; len: SIZE_T; op: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_att_string(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_att_uchar(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_att_uchar(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_att_schar(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PShortInt): Integer; cdecl; external DLLNAME;
function nc_get_att_schar(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PShortInt): Integer; cdecl; external DLLNAME;
function nc_put_att_short(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PSmallint): Integer; cdecl; external DLLNAME;
function nc_get_att_short(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PSmallint): Integer; cdecl; external DLLNAME;
function nc_put_att_int(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PInteger): Integer; cdecl; external DLLNAME;
function nc_get_att_int(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PInteger): Integer; cdecl; external DLLNAME;
function nc_put_att_long(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PLongInt): Integer; cdecl; external DLLNAME;
function nc_get_att_long(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PLongInt): Integer; cdecl; external DLLNAME;
function nc_put_att_float(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PSingle): Integer; cdecl; external DLLNAME;
function nc_get_att_float(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PSingle): Integer; cdecl; external DLLNAME;
function nc_put_att_double(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PDouble): Integer; cdecl; external DLLNAME;
function nc_get_att_double(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PDouble): Integer; cdecl; external DLLNAME;
function nc_put_att_ushort(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PWord): Integer; cdecl; external DLLNAME;
function nc_get_att_ushort(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PWord): Integer; cdecl; external DLLNAME;
function nc_put_att_uint(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PCardinal): Integer; cdecl; external DLLNAME;
function nc_get_att_uint(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PCardinal): Integer; cdecl; external DLLNAME;
function nc_put_att_longlong(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PInt64): Integer; cdecl; external DLLNAME;
function nc_get_att_longlong(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PInt64): Integer; cdecl; external DLLNAME;
function nc_put_att_ulonglong(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PUInt64): Integer; cdecl; external DLLNAME;
function nc_get_att_ulonglong(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PUInt64): Integer; cdecl; external DLLNAME;
function nc_def_var(ncid: Integer; name: PAnsiChar; xtype: TNCType; ndims: Integer; dimidsp: PInteger; varidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_var(ncid: Integer; varid: Integer; name: PAnsiChar; xtypep: PNCType; ndimsp: PInteger; dimidsp: PInteger; nattsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_varid(ncid: Integer; name: PAnsiChar; varidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_varname(ncid: Integer; varid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_inq_vartype(ncid: Integer; varid: Integer; xtypep: PNCType): Integer; cdecl; external DLLNAME;
function nc_inq_varndims(ncid: Integer; varid: Integer; ndimsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_vardimid(ncid: Integer; varid: Integer; dimidsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_inq_varnatts(ncid: Integer; varid: Integer; nattsp: PInteger): Integer; cdecl; external DLLNAME;
function nc_rename_var(ncid: Integer; varid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_copy_var(ncid_in: Integer; varid: Integer; ncid_out: Integer): Integer; cdecl; external DLLNAME;
function nc_put_var1_text(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_var1_text(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_var1_uchar(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_var1_uchar(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_var1_schar(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PShortInt): Integer; cdecl; external DLLNAME;
function nc_get_var1_schar(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PShortInt): Integer; cdecl; external DLLNAME;
function nc_put_var1_short(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PSmallint): Integer; cdecl; external DLLNAME;
function nc_get_var1_short(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PSmallint): Integer; cdecl; external DLLNAME;
function nc_put_var1_int(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PInteger): Integer; cdecl; external DLLNAME;
function nc_get_var1_int(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PInteger): Integer; cdecl; external DLLNAME;
function nc_put_var1_long(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PLongInt): Integer; cdecl; external DLLNAME;
function nc_get_var1_long(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PLongInt): Integer; cdecl; external DLLNAME;
function nc_put_var1_float(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PSingle): Integer; cdecl; external DLLNAME;
function nc_get_var1_float(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PSingle): Integer; cdecl; external DLLNAME;
function nc_put_var1_double(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PDouble): Integer; cdecl; external DLLNAME;
function nc_get_var1_double(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PDouble): Integer; cdecl; external DLLNAME;
function nc_put_var1_ushort(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PWord): Integer; cdecl; external DLLNAME;
function nc_get_var1_ushort(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PWord): Integer; cdecl; external DLLNAME;
function nc_put_var1_uint(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PCardinal): Integer; cdecl; external DLLNAME;
function nc_get_var1_uint(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PCardinal): Integer; cdecl; external DLLNAME;
function nc_put_var1_longlong(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PInt64): Integer; cdecl; external DLLNAME;
function nc_get_var1_longlong(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PInt64): Integer; cdecl; external DLLNAME;
function nc_put_var1_ulonglong(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PUInt64): Integer; cdecl; external DLLNAME;
function nc_get_var1_ulonglong(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PUInt64): Integer; cdecl; external DLLNAME;
function nc_put_var1_string(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_var1_string(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_vara_text(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_vara_text(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_vara_uchar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_vara_uchar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_vara_schar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PShortInt): Integer; cdecl; external DLLNAME;
function nc_get_vara_schar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PShortInt): Integer; cdecl; external DLLNAME;
function nc_put_vara_short(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PSmallint): Integer; cdecl; external DLLNAME;
function nc_get_vara_short(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PSmallint): Integer; cdecl; external DLLNAME;
function nc_put_vara_int(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PInteger): Integer; cdecl; external DLLNAME;
function nc_get_vara_int(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PInteger): Integer; cdecl; external DLLNAME;
function nc_put_vara_long(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PLongInt): Integer; cdecl; external DLLNAME;
function nc_get_vara_long(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PLongInt): Integer; cdecl; external DLLNAME;
function nc_put_vara_float(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PSingle): Integer; cdecl; external DLLNAME;
function nc_get_vara_float(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PSingle): Integer; cdecl; external DLLNAME;
function nc_put_vara_double(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PDouble): Integer; cdecl; external DLLNAME;
function nc_get_vara_double(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PDouble): Integer; cdecl; external DLLNAME;
function nc_put_vara_ushort(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PWord): Integer; cdecl; external DLLNAME;
function nc_get_vara_ushort(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PWord): Integer; cdecl; external DLLNAME;
function nc_put_vara_uint(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PCardinal): Integer; cdecl; external DLLNAME;
function nc_get_vara_uint(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PCardinal): Integer; cdecl; external DLLNAME;
function nc_put_vara_longlong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PInt64): Integer; cdecl; external DLLNAME;
function nc_get_vara_longlong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PInt64): Integer; cdecl; external DLLNAME;
function nc_put_vara_ulonglong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PUInt64): Integer; cdecl; external DLLNAME;
function nc_get_vara_ulonglong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PUInt64): Integer; cdecl; external DLLNAME;
function nc_put_vara_string(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_vara_string(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_vars_text(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_vars_text(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_vars_uchar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_vars_uchar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_vars_schar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PShortInt): Integer; cdecl; external DLLNAME;
function nc_get_vars_schar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PShortInt): Integer; cdecl; external DLLNAME;
function nc_put_vars_short(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PSmallint): Integer; cdecl; external DLLNAME;
function nc_get_vars_short(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PSmallint): Integer; cdecl; external DLLNAME;
function nc_put_vars_int(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PInteger): Integer; cdecl; external DLLNAME;
function nc_get_vars_int(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PInteger): Integer; cdecl; external DLLNAME;
function nc_put_vars_long(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PLongInt): Integer; cdecl; external DLLNAME;
function nc_get_vars_long(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PLongInt): Integer; cdecl; external DLLNAME;
function nc_put_vars_float(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PSingle): Integer; cdecl; external DLLNAME;
function nc_get_vars_float(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PSingle): Integer; cdecl; external DLLNAME;
function nc_put_vars_double(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PDouble): Integer; cdecl; external DLLNAME;
function nc_get_vars_double(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PDouble): Integer; cdecl; external DLLNAME;
function nc_put_vars_ushort(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PWord): Integer; cdecl; external DLLNAME;
function nc_get_vars_ushort(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PWord): Integer; cdecl; external DLLNAME;
function nc_put_vars_uint(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PCardinal): Integer; cdecl; external DLLNAME;
function nc_get_vars_uint(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PCardinal): Integer; cdecl; external DLLNAME;
function nc_put_vars_longlong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PInt64): Integer; cdecl; external DLLNAME;
function nc_get_vars_longlong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PInt64): Integer; cdecl; external DLLNAME;
function nc_put_vars_ulonglong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PUInt64): Integer; cdecl; external DLLNAME;
function nc_get_vars_ulonglong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PUInt64): Integer; cdecl; external DLLNAME;
function nc_put_vars_string(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_vars_string(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_varm_text(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_varm_text(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_varm_uchar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_varm_uchar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_varm_schar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PShortInt): Integer; cdecl; external DLLNAME;
function nc_get_varm_schar(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PShortInt): Integer; cdecl; external DLLNAME;
function nc_put_varm_short(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PSmallint): Integer; cdecl; external DLLNAME;
function nc_get_varm_short(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PSmallint): Integer; cdecl; external DLLNAME;
function nc_put_varm_int(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PInteger): Integer; cdecl; external DLLNAME;
function nc_get_varm_int(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PInteger): Integer; cdecl; external DLLNAME;
function nc_put_varm_long(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PLongInt): Integer; cdecl; external DLLNAME;
function nc_get_varm_long(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PLongInt): Integer; cdecl; external DLLNAME;
function nc_put_varm_float(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PSingle): Integer; cdecl; external DLLNAME;
function nc_get_varm_float(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PSingle): Integer; cdecl; external DLLNAME;
function nc_put_varm_double(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PDouble): Integer; cdecl; external DLLNAME;
function nc_get_varm_double(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PDouble): Integer; cdecl; external DLLNAME;
function nc_put_varm_ushort(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PWord): Integer; cdecl; external DLLNAME;
function nc_get_varm_ushort(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PWord): Integer; cdecl; external DLLNAME;
function nc_put_varm_uint(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PCardinal): Integer; cdecl; external DLLNAME;
function nc_get_varm_uint(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PCardinal): Integer; cdecl; external DLLNAME;
function nc_put_varm_longlong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PInt64): Integer; cdecl; external DLLNAME;
function nc_get_varm_longlong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PInt64): Integer; cdecl; external DLLNAME;
function nc_put_varm_ulonglong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PUInt64): Integer; cdecl; external DLLNAME;
function nc_get_varm_ulonglong(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PUInt64): Integer; cdecl; external DLLNAME;
function nc_put_varm_string(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_varm_string(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_var_text(ncid: Integer; varid: Integer; op: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_var_text(ncid: Integer; varid: Integer; ip: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_var_uchar(ncid: Integer; varid: Integer; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_var_uchar(ncid: Integer; varid: Integer; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_var_schar(ncid: Integer; varid: Integer; op: PShortInt): Integer; cdecl; external DLLNAME;
function nc_get_var_schar(ncid: Integer; varid: Integer; ip: PShortInt): Integer; cdecl; external DLLNAME;
function nc_put_var_short(ncid: Integer; varid: Integer; op: PSmallint): Integer; cdecl; external DLLNAME;
function nc_get_var_short(ncid: Integer; varid: Integer; ip: PSmallint): Integer; cdecl; external DLLNAME;
function nc_put_var_int(ncid: Integer; varid: Integer; op: PInteger): Integer; cdecl; external DLLNAME;
function nc_get_var_int(ncid: Integer; varid: Integer; ip: PInteger): Integer; cdecl; external DLLNAME;
function nc_put_var_long(ncid: Integer; varid: Integer; op: PLongInt): Integer; cdecl; external DLLNAME;
function nc_get_var_long(ncid: Integer; varid: Integer; ip: PLongInt): Integer; cdecl; external DLLNAME;
function nc_put_var_float(ncid: Integer; varid: Integer; op: PSingle): Integer; cdecl; external DLLNAME;
function nc_get_var_float(ncid: Integer; varid: Integer; ip: PSingle): Integer; cdecl; external DLLNAME;
function nc_put_var_double(ncid: Integer; varid: Integer; op: PDouble): Integer; cdecl; external DLLNAME;
function nc_get_var_double(ncid: Integer; varid: Integer; ip: PDouble): Integer; cdecl; external DLLNAME;
function nc_put_var_ushort(ncid: Integer; varid: Integer; op: PWord): Integer; cdecl; external DLLNAME;
function nc_get_var_ushort(ncid: Integer; varid: Integer; ip: PWord): Integer; cdecl; external DLLNAME;
function nc_put_var_uint(ncid: Integer; varid: Integer; op: PCardinal): Integer; cdecl; external DLLNAME;
function nc_get_var_uint(ncid: Integer; varid: Integer; ip: PCardinal): Integer; cdecl; external DLLNAME;
function nc_put_var_longlong(ncid: Integer; varid: Integer; op: PInt64): Integer; cdecl; external DLLNAME;
function nc_get_var_longlong(ncid: Integer; varid: Integer; ip: PInt64): Integer; cdecl; external DLLNAME;
function nc_put_var_ulonglong(ncid: Integer; varid: Integer; op: PUInt64): Integer; cdecl; external DLLNAME;
function nc_get_var_ulonglong(ncid: Integer; varid: Integer; ip: PUInt64): Integer; cdecl; external DLLNAME;
function nc_put_var_string(ncid: Integer; varid: Integer; op: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_get_var_string(ncid: Integer; varid: Integer; ip: PPAnsiChar): Integer; cdecl; external DLLNAME;
function nc_put_att_ubyte(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: SIZE_T; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_att_ubyte(ncid: Integer; varid: Integer; name: PAnsiChar; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_var1_ubyte(ncid: Integer; varid: Integer; indexp: PSIZE_T; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_var1_ubyte(ncid: Integer; varid: Integer; indexp: PSIZE_T; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_vara_ubyte(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_vara_ubyte(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_vars_ubyte(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_vars_ubyte(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_varm_ubyte(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_varm_ubyte(ncid: Integer; varid: Integer; startp: PSIZE_T; countp: PSIZE_T; stridep: PNativeInt; imapp: PNativeInt; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_put_var_ubyte(ncid: Integer; varid: Integer; op: PByte): Integer; cdecl; external DLLNAME;
function nc_get_var_ubyte(ncid: Integer; varid: Integer; ip: PByte): Integer; cdecl; external DLLNAME;
function nc_show_metadata(ncid: Integer): Integer; cdecl; external DLLNAME;
function nc__create_mp(path: PAnsiChar; cmode: Integer; initialsz: SIZE_T; basepe: Integer; chunksizehintp: PSIZE_T; ncidp: PInteger): Integer; cdecl; external DLLNAME;
function nc__open_mp(path: PAnsiChar; mode: Integer; basepe: Integer; chunksizehintp: PSIZE_T; ncidp: PInteger): Integer; cdecl; external DLLNAME;
function nc_delete(path: PAnsiChar): Integer; cdecl; external DLLNAME;
function nc_delete_mp(path: PAnsiChar; basepe: Integer): Integer; cdecl; external DLLNAME;
function nc_set_base_pe(ncid: Integer; pe: Integer): Integer; cdecl; external DLLNAME;
function nc_inq_base_pe(ncid: Integer; pe: PInteger): Integer; cdecl; external DLLNAME;
function nctypelen(datatype: TNCType): Integer; cdecl; external DLLNAME;
function nccreate(path: PAnsiChar; cmode: Integer): Integer; cdecl; external DLLNAME;
function ncopen(path: PAnsiChar; mode: Integer): Integer; cdecl; external DLLNAME;
function ncsetfill(ncid: Integer; fillmode: Integer): Integer; cdecl; external DLLNAME;
function ncredef(ncid: Integer): Integer; cdecl; external DLLNAME;
function ncendef(ncid: Integer): Integer; cdecl; external DLLNAME;
function ncsync(ncid: Integer): Integer; cdecl; external DLLNAME;
function ncabort(ncid: Integer): Integer; cdecl; external DLLNAME;
function ncclose(ncid: Integer): Integer; cdecl; external DLLNAME;
function ncinquire(ncid: Integer; ndimsp: PInteger; nvarsp: PInteger; nattsp: PInteger; unlimdimp: PInteger): Integer; cdecl; external DLLNAME;
function ncdimdef(ncid: Integer; name: PAnsiChar; len: LongInt): Integer; cdecl; external DLLNAME;
function ncdimid(ncid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function ncdiminq(ncid: Integer; dimid: Integer; name: PAnsiChar; lenp: PLongInt): Integer; cdecl; external DLLNAME;
function ncdimrename(ncid: Integer; dimid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function ncattput(ncid: Integer; varid: Integer; name: PAnsiChar; xtype: TNCType; len: Integer; op: Pointer): Integer; cdecl; external DLLNAME;
function ncattinq(ncid: Integer; varid: Integer; name: PAnsiChar; xtypep: PNCType; lenp: PInteger): Integer; cdecl; external DLLNAME;
function ncattget(ncid: Integer; varid: Integer; name: PAnsiChar; ip: Pointer): Integer; cdecl; external DLLNAME;
function ncattcopy(ncid_in: Integer; varid_in: Integer; name: PAnsiChar; ncid_out: Integer; varid_out: Integer): Integer; cdecl; external DLLNAME;
function ncattname(ncid: Integer; varid: Integer; attnum: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function ncattrename(ncid: Integer; varid: Integer; name: PAnsiChar; newname: PAnsiChar): Integer; cdecl; external DLLNAME;
function ncattdel(ncid: Integer; varid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function ncvardef(ncid: Integer; name: PAnsiChar; xtype: TNCType; ndims: Integer; dimidsp: PInteger): Integer; cdecl; external DLLNAME;
function ncvarid(ncid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function ncvarinq(ncid: Integer; varid: Integer; name: PAnsiChar; xtypep: PNCType; ndimsp: PInteger; dimidsp: PInteger; nattsp: PInteger): Integer; cdecl; external DLLNAME;
function ncvarput1(ncid: Integer; varid: Integer; indexp: PLongInt; op: Pointer): Integer; cdecl; external DLLNAME;
function ncvarget1(ncid: Integer; varid: Integer; indexp: PLongInt; ip: Pointer): Integer; cdecl; external DLLNAME;
function ncvarput(ncid: Integer; varid: Integer; startp: PLongInt; countp: PLongInt; op: Pointer): Integer; cdecl; external DLLNAME;
function ncvarget(ncid: Integer; varid: Integer; startp: PLongInt; countp: PLongInt; ip: Pointer): Integer; cdecl; external DLLNAME;
function ncvarputs(ncid: Integer; varid: Integer; startp: PLongInt; countp: PLongInt; stridep: PLongInt; op: Pointer): Integer; cdecl; external DLLNAME;
function ncvargets(ncid: Integer; varid: Integer; startp: PLongInt; countp: PLongInt; stridep: PLongInt; ip: Pointer): Integer; cdecl; external DLLNAME;
function ncvarputg(ncid: Integer; varid: Integer; startp: PLongInt; countp: PLongInt; stridep: PLongInt; imapp: PLongInt; op: Pointer): Integer; cdecl; external DLLNAME;
function ncvargetg(ncid: Integer; varid: Integer; startp: PLongInt; countp: PLongInt; stridep: PLongInt; imapp: PLongInt; ip: Pointer): Integer; cdecl; external DLLNAME;
function ncvarrename(ncid: Integer; varid: Integer; name: PAnsiChar): Integer; cdecl; external DLLNAME;
function ncrecinq(ncid: Integer; nrecvarsp: PInteger; recvaridsp: PInteger; recsizesp: PLongInt): Integer; cdecl; external DLLNAME;
function ncrecget(ncid: Integer; recnum: LongInt; datap: PPointer): Integer; cdecl; external DLLNAME;
function ncrecput(ncid: Integer; recnum: LongInt; datap: PPointer): Integer; cdecl; external DLLNAME;
function nc_finalize(): Integer; cdecl; external DLLNAME;


implementation

end.